# Generated by Django 5.2 on 2025-05-21 03:02

import rentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adress', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц')),
                ('street_or_district', models.CharField(max_length=255, verbose_name='Улица или микрорайон')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('intercom_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон')),
                ('rooms', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Количество комнат')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('total_floors', models.PositiveSmallIntegerField(verbose_name='Этажей в доме')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая площадь (м²)')),
                ('area_living', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жилая площадь (м²)')),
                ('area_kitchen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь кухни (м²)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Image files name')),
                ('file', models.FileField(upload_to='images/', validators=[rentapp.models.validate_image], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐'), (6, '6 ⭐'), (7, '7 ⭐'), (8, '8 ⭐'), (9, '9 ⭐'), (10, '10 ⭐')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
